# Generated by Django 4.0.6 on 2022-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('startDate', models.DateField(verbose_name='startDate')),
                ('endDate', models.DateField(verbose_name='endDate')),
            ],
        ),
        migrations.CreateModel(
            name='TabCenterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.TextField(max_length=255, verbose_name='full name')),
                ('paradigm', models.TextField(default='Empty', verbose_name='paradigm')),
                ('institution', models.TextField(default='Empty', verbose_name='institution')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
