# Generated by Django 4.0.6 on 2022-07-27 08:22

import TabCenterApp.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('startDate', models.DateField(verbose_name='startDate')),
                ('endDate', models.DateField(verbose_name='endDate')),
                ('location', models.CharField(default='x', max_length=2, verbose_name='location')),
                ('formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='format'), default=TabCenterApp.models.Tournament.get_default_format, size=None, verbose_name='format')),
                ('price', models.FloatField(verbose_name='price')),
                ('online', models.BooleanField(verbose_name='online')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('registration', models.BooleanField(verbose_name='registration')),
            ],
        ),
        migrations.CreateModel(
            name='TabCenterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.TextField(max_length=255, verbose_name='full name')),
                ('paradigm', models.TextField(default='Empty', verbose_name='paradigm')),
                ('institution', models.TextField(default='Empty', verbose_name='institution')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
