# Generated by Django 4.0.6 on 2022-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabCenterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('startDate', models.DateField(verbose_name='startDate')),
                ('endDate', models.DateField(verbose_name='endDate')),
            ],
        ),
    ]
