# Generated by Django 4.0.6 on 2022-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabCenterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
