# Generated by Django 4.0.6 on 2022-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabCenterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='entries',
            field=models.ManyToManyField(blank=True, to='TabCenterApp.entry'),
        ),
    ]
